# Generated by Django 6.0.1 on 2026-01-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_equipmentdataset_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentdataset',
            name='original_filename',
            field=models.CharField(default='dataset.csv', max_length=255),
        ),
    ]
